In [1]:
import pandas as pd
import numpy as np
import datetime as dt

In [35]:
df=pd.read_csv("/Users/wojtekmarszalek/Desktop/Sales Data.csv")

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185950 entries, 0 to 185949
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        185950 non-null  int64
 1   Order ID          185950 non-null  int64
 2   Product           185950 non-null  object
 3   Quantity Ordered  185950 non-null  int64
 4   Price Each        185950 non-null  float64
 5   Order Date        185950 non-null  object
 6   Purchase Address  185950 non-null  object
 7   Month             185950 non-null  int64
 8   Sales             185950 non-null  float64
 9   City              185950 non-null  object
 10  Hour              185950 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 15.6+ MB

In [37]:
df.head(15)

,Unnamed: 0,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Sales,City,Hour
0,0,295665,Macbook Pro Laptop,1,1700.00,2019-12-30 00:01:00,"136 Church St, New York City, NY 10001",12,1700.00,New York City,0
1,1,295666,LG Washing Machine,1,600.00,2019-12-29 07:03:00,"562 2nd St, New York City, NY 10001",12,600.00,New York City,7
2,2,295667,USB-C Charging Cable,1,11.95,2019-12-12 18:21:00,"277 Main St, New York City, NY 10001",12,11.95,New York City,18
3,3,295668,27in FHD Monitor,1,149.99,2019-12-22 15:13:00,"410 6th St, San Francisco, CA 94016",12,149.99,San Francisco,15
4,4,295669,USB-C Charging Cable,1,11.95,2019-12-18 12:38:00,"43 Hill St, Atlanta, GA 30301",12,11.95,Atlanta,12
5,5,295670,AA Batteries (4-pack),1,3.84,2019-12-31 22:58:00,"200 Jefferson St, New York City, NY 10001",12,3.84,New York City,22
6,6,295671,USB-C Charging Cable,1,11.95,2019-12-16 15:10:00,"928 12th St, Portland, OR 97035",12,11.95,Portland,15
7,7,295672,USB-C Charging Cable,2,11.95,2019-12-13 09:29:00,"813 Hickory St, Dallas, TX 75001",12,23.90,Dallas,9
8,8,295673,Bose SoundSport Headphones,1,99.99,2019-12-15 23:26:00,"718 Wilson St, Dallas, TX 75001",12,99.99,Dallas,23
9,9,295674,AAA Batteries (4-pack),4,2.99,2019-12-28 11:51:00,"77 7th St, Dallas, TX 75001",12,11.96,Dallas,11
10,10,295675,USB-C Charging Cable,2,11.95,2019-12-13 13:52:00,"594 1st St, San Francisco, CA 94016",12,23.90,San Francisco,13
11,11,295676,ThinkPad Laptop,1,999.99,2019-12-28 17:19:00,"410 Lincoln St, Los Angeles, CA 90001",12,999.99,Los Angeles,17
12,12,295677,AA Batteries (4-pack),2,3.84,2019-12-20 19:19:00,"866 Pine St, Boston, MA 02215",12,7.68,Boston,19
13,13,295678,AAA Batteries (4-pack),2,2.99,2019-12-06 09:38:00,"187 Lincoln St, Dallas, TX 75001",12,5.98,Dallas,9
14,14,295679,USB-C Charging Cable,1,11.95,2019-12-25 09:39:00,"902 2nd St, Dallas, TX 75001",12,11.95,Dallas,9

In [38]:
df["Order Date"]=pd.to_datetime(df["Order Date"]).dt.date

In [39]:
df.drop("Unnamed: 0",inplace=True,axis=1)

In [40]:
df[["Street", "City", "Postal Code"]]=df['Purchase Address'].str.split(",", expand=True)

In [41]:
df

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Sales,City,Hour,Street,Postal Code
0,295665,Macbook Pro Laptop,1,1700.00,2019-12-30,"136 Church St, New York City, NY 10001",12,1700.00,New York City,0,136 Church St,NY 10001
1,295666,LG Washing Machine,1,600.00,2019-12-29,"562 2nd St, New York City, NY 10001",12,600.00,New York City,7,562 2nd St,NY 10001
2,295667,USB-C Charging Cable,1,11.95,2019-12-12,"277 Main St, New York City, NY 10001",12,11.95,New York City,18,277 Main St,NY 10001
3,295668,27in FHD Monitor,1,149.99,2019-12-22,"410 6th St, San Francisco, CA 94016",12,149.99,San Francisco,15,410 6th St,CA 94016
4,295669,USB-C Charging Cable,1,11.95,2019-12-18,"43 Hill St, Atlanta, GA 30301",12,11.95,Atlanta,12,43 Hill St,GA 30301
...,...,...,...,...,...,...,...,...,...,...,...,...
185945,222905,AAA Batteries (4-pack),1,2.99,2019-06-07,"795 Pine St, Boston, MA 02215",6,2.99,Boston,19,795 Pine St,MA 02215
185946,222906,27in FHD Monitor,1,149.99,2019-06-01,"495 North St, New York City, NY 10001",6,149.99,New York City,19,495 North St,NY 10001
185947,222907,USB-C Charging Cable,1,11.95,2019-06-22,"319 Ridge St, San Francisco, CA 94016",6,11.95,San Francisco,18,319 Ridge St,CA 94016
185948,222908,USB-C Charging Cable,1,11.95,2019-06-26,"916 Main St, San Francisco, CA 94016",6,11.95,San Francisco,18,916 Main St,CA 94016
185949,222909,AAA Batteries (4-pack),1,2.99,2019-06-25,"209 11th St, Atlanta, GA 30301",6,2.99,Atlanta,14,209 11th St,GA 30301

In [42]:
df.drop("Purchase Address", inplace=True, axis=1)

In [43]:
days=[]
for i in df["Order Date"]:
    days.append(i.day)

In [44]:
df["Day"]=days

In [45]:
df.drop("Order Date", axis=1, inplace=True)

In [46]:
df=df[["Order ID", "Product","Quantity Ordered", "Month", "Day", "Price Each", "Sales", "City", "Hour", "Street", "Postal Code"]]

In [47]:
df

,Order ID,Product,Quantity Ordered,Month,Day,Price Each,Sales,City,Hour,Street,Postal Code
0,295665,Macbook Pro Laptop,1,12,30,1700.00,1700.00,New York City,0,136 Church St,NY 10001
1,295666,LG Washing Machine,1,12,29,600.00,600.00,New York City,7,562 2nd St,NY 10001
2,295667,USB-C Charging Cable,1,12,12,11.95,11.95,New York City,18,277 Main St,NY 10001
3,295668,27in FHD Monitor,1,12,22,149.99,149.99,San Francisco,15,410 6th St,CA 94016
4,295669,USB-C Charging Cable,1,12,18,11.95,11.95,Atlanta,12,43 Hill St,GA 30301
...,...,...,...,...,...,...,...,...,...,...,...
185945,222905,AAA Batteries (4-pack),1,6,7,2.99,2.99,Boston,19,795 Pine St,MA 02215
185946,222906,27in FHD Monitor,1,6,1,149.99,149.99,New York City,19,495 North St,NY 10001
185947,222907,USB-C Charging Cable,1,6,22,11.95,11.95,San Francisco,18,319 Ridge St,CA 94016
185948,222908,USB-C Charging Cable,1,6,26,11.95,11.95,San Francisco,18,916 Main St,CA 94016
185949,222909,AAA Batteries (4-pack),1,6,25,2.99,2.99,Atlanta,14,209 11th St,GA 30301